name: Docker - Debian
on:
  schedule:
    - cron: '57 12 * * 1'
  push:
    branches: [ "main" ]

env:
  SUFFIX: 
  DOCKERFILE: debian/Dockerfile

jobs:
  delegate:
    uses: ./.github/workflows/docker-publish.yml@main
    secrets: inherit
    with:
      dockerfile: ${{ env.DOCKERFILE }}
      checkout: master
      suffix: ${{ env.SUFFIX }}
