name: Docker - Alpine
on:
  schedule:
    - cron: '57 12 * * 1'
  push:
    branches: [ "main" ]

env:
  SUFFIX: -alpine
  DOCKERFILE: alpine/Dockerfile

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      dockerfile: ${{ env.DOCKERFILE }}
      suffix: ${{ env.SUFFIX }}
    steps:
      - run: echo "Exposing env vars"
  invoke-build:
    uses: ./.github/workflows/docker-publish.yml
    needs: vars
    secrets: inherit
    with:
      dockerfile: ${{ needs.vars.outputs.dockerfile }}
      checkout: master
      suffix: ${{ needs.vars.outputs.suffix }}
