name: Docker Debian
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Git branch to checkout"
        default: ""
        required: false
  schedule:
    - cron:  '07 16 * * THU'

jobs:
  run-build:
    uses: ./.github/workflows/docker-publish.yml
    secrets: inherit
    with:
      osname: 'debian'
      osstablever: 'bookworm'
      pythonvers: '[ "3.10", "3.11"]'
      osvers: '[ "bookworm" ]'
      branch: '${{ github.event.inputs.branch }}'
