name: Docker Alpine
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Git branch to checkout"
        default: ""
        required: false
  schedule:
    - cron:  '57 16 * * THU'

jobs:
  run-build:
    uses: ./.github/workflows/docker-publish.yml
    secrets: inherit
    with:
      osname: 'alpine'
      osstablever: '3.19'
      pythonvers: '[ "3.11", "3.12" ]'
      osvers: '[ "3.19", "3.20" ]'
      branch: '${{ github.event.inputs.branch }}'
