name: Docker
on:
  workflow_call:
    inputs:
      dockerfile:
        description: "Path to the Dockerfile"
        required: true
        default: debian/Dockerfile
        type: string
      checkout:
        description: "What to git checkout"
        required: true
        default: master
        type: string
      suffix:
        description: "What to suffix the tag with"
        required: false
        default:
        type: string

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKER_USER }}/sd-test

jobs:
  build:
    env:
      DOCKERFILE: ${{ inputs.dockerfile }}
      CHECKOUT: ${{ inputs.checkout }}
      SUFFIX: ${{ inputs.suffix }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: main

      - name: Checkout upstream
        uses: actions/checkout@v3
        with:
          repository: eliasdoehne/stellaris-dashboard
          path: stellaris-dashboard

      # https://github.com/docker/setup-buildx-action
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          working-directory: ./main

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          working-directory: ./stellaris-dashboard
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=edge
            type=semver,pattern={{version}}
          flavor: |
            suffix=${{ env.SUFFIX }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
#      - name: Build and push Docker image
#        id: build-and-push
#        uses: docker/build-push-action@v3
#        with:
#          working-directory: ./main
#          context: .
#          file: ${{ env.DOCKERFILE }}
#          build-args: |
#            SD_TAG=${{ env.CHECKOUT }}
#          push: ${{ github.event_name != 'pull_request' }}
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
