name: Docker - Alpine
on:
  schedule:
    - cron: '57 12 * * 1'
  push:
    branches: [ "main" ]

env:
  SUFFIX: -alpine
  DOCKERFILE: alpine/Dockerfile

jobs:
  delegate:
    uses: ./.github/workflows/docker-publish.yml
    secrets: inherit
    with:
      dockerfile: ${{ env.DOCKERFILE }}
      checkout: master
      suffix: ${{ env.SUFFIX }}
